spring.application.name=ex25-branch

server.port=8091

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=1234

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.ex25Branch.domain
mybatis.configuration.map-underscore-to-camel-case=false

logging.level.com.skc.mybatis.mapper=DEBUG

server.servlet.encoding.charset=UTF-8

server.servlet.encoding.enabled=true

server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true